import React from 'react';
import EmblaCarousel from '@/components/EmblaCarousel';

const SoftMemoryCarousel = () => {
  const images = [
    '/img/projects/photography/moments/soft15.jpg',
    '/img/projects/photography/moments/soft3.jpg',
    '/img/projects/photography/moments/soft31.jpg',
    '/img/projects/photography/moments/soft1.jpg',
    '/img/projects/photography/moments/soft2.jpg',
    '/img/projects/photography/moments/soft4.jpg',
    '/img/projects/photography/moments/soft5.jpg',
    '/img/projects/photography/moments/soft6.jpg',
    '/img/projects/photography/moments/soft7.jpg',
    '/img/projects/photography/moments/soft8.jpg',
    '/img/projects/photography/moments/soft9.jpg',
    '/img/projects/photography/moments/soft10.jpg',
    '/img/projects/photography/moments/soft11.jpg',
    '/img/projects/photography/moments/soft12.jpg',
    '/img/projects/photography/moments/soft13.jpg',
    '/img/projects/photography/moments/soft14.jpg',
    '/img/projects/photography/moments/soft16.jpg',
    '/img/projects/photography/moments/soft17.jpg',
    '/img/projects/photography/moments/soft18.jpg',
    // "/img/projects/photography/moments/soft19.jpg",
    '/img/projects/photography/moments/soft20.jpg',
    '/img/projects/photography/moments/soft21.jpg',
    '/img/projects/photography/moments/soft22.jpg',
    '/img/projects/photography/moments/soft23.jpg',
    '/img/projects/photography/moments/soft24.jpg',
    '/img/projects/photography/moments/soft25.jpg',
    '/img/projects/photography/moments/soft26.jpg',
    '/img/projects/photography/moments/soft27.jpg',
    '/img/projects/photography/moments/soft28.jpg',
    '/img/projects/photography/moments/soft29.jpg',
    '/img/projects/photography/moments/soft30.jpg',
    '/img/projects/photography/moments/soft32.jpg',
    '/img/projects/photography/moments/soft33.jpg',
    '/img/projects/photography/moments/soft34.jpg',
    '/img/projects/photography/moments/soft35.jpg',
    '/img/projects/photography/moments/soft36.jpg',
    '/img/projects/photography/moments/soft37.jpg',
    '/img/projects/photography/moments/soft38.jpg',
    '/img/projects/photography/moments/soft39.jpg',
    '/img/projects/photography/moments/soft40.jpg',
    '/img/projects/photography/moments/soft41.jpg',
    // "/img/projects/photography/moments/soft42.jpg",
    '/img/projects/photography/moments/soft43.jpg',
    '/img/projects/photography/moments/soft44.jpg',
    '/img/projects/photography/moments/soft45.jpg',
    '/img/projects/photography/moments/soft46.jpg',
    '/img/projects/photography/moments/soft47.jpg',
    '/img/projects/photography/moments/soft48.jpg',
    '/img/projects/photography/moments/soft49.jpg',
    '/img/projects/photography/moments/soft50.jpg',
    '/img/projects/photography/moments/soft51.jpg',
    // "/img/projects/photography/moments/soft52.jpg",
    '/img/projects/photography/moments/soft53.jpg',
    '/img/projects/photography/moments/soft54.jpg',
    '/img/projects/photography/moments/soft55.jpg',
    '/img/projects/photography/moments/soft56.jpg',
    '/img/projects/photography/moments/soft57.jpg',
  ];

  return <EmblaCarousel images={images} />;
};

export default SoftMemoryCarousel;
