import React from "react";
import PageInfo from "@/components/PageInfo"; // Adjust the path as per your project structure

const Page = () => {
  return (
    <div>
      <PageInfo
        title="18:17"
        iframeSrc="https://www.youtube.com/embed/7_FHoUuEkPg?si=sidMiz2oRLTir8ax"
        subtitle="When Sun Goes Down"
        textContent={`<em>18:17</em> is a collaborative audiovisual performance featuring live saxophone, experimental music, and real-time visual storytelling through code-generated imagery. Created by three artists — Musician and Computer Programmer Danny Meyer, Visual Artist Yan and Yifan — the project explores the contrast and interplay between analog warmth and surreal digital landscapes. <br /><br />
          The performance consists of nine musical pieces in total. Eight are original compositions, generated by  <a href=' https://www.weresocool.org/tutorials/getting_started'  target=' _blank'  rel=' noopener noreferrer' style='text-decoration:underline' ><em>Weresocool</em></a>, a custom programming language written by Danny Meyer that geometrically composes microtonal music. One of the pieces is a reimagining of <em>Bach’s WTC I Prelude No. 3 in C-sharp major (BWV 848)</ em>, presented in three variations: first as written, second as a full inversion (where even the visual triangles are flipped), and finally in an accelerated version.
          <br /> <br />Each musical piece is paired with a unique visual scene. For the opening piece <em>“Rest Relax”</ em> and <em> Bach’s prelude </ em>, the visuals are edited from footage of old films, evoking a nostalgic, analog texture. For the remaining six pieces, original CG scenes were created in Unreal Engine, combining with geometric sequences generated by  <a href=' https://www.weresocool.org/tutorials/getting_started'  target=' _blank'  rel=' noopener noreferrer' style='text-decoration:underline' ><em>Weresocool</em></a> to build alien-like dreamscapes that mirror the experimental sounds.`}
        imagePaths={[
          {
            type: "image",
            src: "/img/projects/performance/1817/1.jpg",
          },
          {
            type: "image",
            src: "/img/projects/performance/1817/2.jpg",
          },
          {
            type: "image",
            src: "/img/projects/performance/1817/3.jpg",
          },
          {
            type: "image",
            src: "/img/projects/performance/1817/4.png",
          },
        ]}
        textAdditional={
          "We wanted to create a mixed atmosphere with nostalgic film textures and surreal digital environments, offering a visual experience that feels both familiar and otherworldly. The performance was held at UltraSuperNew KURA in Shibuya, Tokyo on April 19, 2025."
        }
        imageAdditional={[{ src: "/img/projects/performance/1817/6.png" }]}
        creditsText={[
          "C R E D I T S",

          "YIFAN ZHUANG & YAN HE <b> CG/ Visual Artist <b/>",
          "DANNY MEYER <b> Sound Artist & Saxophone Player <b/>",
          ,
        ]}
        videoCreditsText={[]}
        specialThanksText={[]}
        additionalVideoSrc="https://www.youtube.com/embed/MbUHZ40ufo0?si=wffAPWFhf252aYWZ"
      />
    </div>
  );
};

export default Page;
