'use client';

import React from 'react';
import ProjectHeader from '@/components/ProjectHeader';
import MediaGrid from '@/components/MediaGrid';

const Page = () => {
  const metadata = [
    { label: 'Year', value: '2025' },
    { label: 'Category', value: 'Live Saxophone, Audio/ visual Performance' },
    { label: 'Venue', value: 'UltraSuperNew KURA, Shibuya' },
    { label: 'Collaborators', value: 'Danny Meyer, Yan He' },
  ];

  const description = [
    '18:17 is a collaborative audiovisual performance featuring live saxophone, experimental music, and real-time visual storytelling through code-generated imagery. Created by three artists — Musician and Computer Programmer Danny Meyer, Visual Artists Yan and Yifan — the project explores the contrast and interplay between analog warmth and surreal digital landscapes.',
    'Each musical piece is paired with a unique visual scene. For the opening piece "Rest Relax" and Bach\'s prelude, the visuals are edited from footage of old films, evoking a nostalgic, analog texture. For the remaining six pieces, original CG scenes were created in Unreal Engine, combining with geometric sequences generated by Weresocool to build alien-like dreamscapes that mirror the experimental sounds.',
  ];

  const mediaItems = [
    {
      type: 'video' as const,
      src: 'https://www.youtube.com/embed/7_FHoUuEkPg?si=sidMiz2oRLTir8ax',
      caption: 'Main Performance',
      width: 100 as const,
      aspectRatio: '16-9',
    },
    {
      type: 'image' as const,
      src: '/img/projects/performance/1817/1.jpg',
      alt: '18:17 Performance Scene 1',
      width: 50 as const,
    },
    {
      type: 'image' as const,
      src: '/img/projects/performance/1817/2.jpg',
      alt: '18:17 Performance Scene 2',
      width: 50 as const,
    },
    {
      type: 'image' as const,
      src: '/img/projects/performance/1817/3.jpg',
      alt: '18:17 Performance Scene 3',
      width: 50 as const,
    },
    {
      type: 'image' as const,
      src: '/img/projects/performance/1817/4.png',
      alt: '18:17 Visual Design',
      width: 50 as const,
    },
    {
      type: 'image' as const,
      src: '/img/projects/performance/1817/5.png',
      alt: '18:17 Visual Scene',
      width: 50 as const,
    },
    {
      type: 'image' as const,
      src: '/img/projects/performance/1817/6.png',
      alt: '18:17 Digital Landscape',
      width: 50 as const,
    },
  ];

  return (
    <div>
      {/* Hero Video - Full width above ProjectHeader */}
      <div style={{ width: '100%', position: 'relative', paddingBottom: '35%' }}>
        <video
          src="/img/projects/performance/1817/1817.mp4"
          autoPlay
          muted
          loop
          playsInline
          style={{
            position: 'absolute',
            top: 0,
            left: 0,
            width: '100%',
            height: '100%',
            objectFit: 'cover',
          }}
        >
          Your browser does not support the video tag.
        </video>
      </div>

      <ProjectHeader title="18:17" description={description} metadata={metadata} />
      <MediaGrid items={mediaItems} />
    </div>
  );
};

export default Page;
