import React from "react";
import PageInfo from "@/components/PageInfo";
import { text } from "stream/consumers";

const About = () => {
  return (
    <div>
      <PageInfo
        iframeSrc="https://player.vimeo.com/video/638304696?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479"
        title="CG of &#39;i dream, i dreamt&#39;"
        subtitle="a dream generated by artificial brain &#39;no.01&#39;"
        textContent={`In dreams of artificial brain ‘No.01’, participants are taken on a journey exploring the emergence of an artificial brain developing digital consciousness.The installation combines CG visuals and footage of 3D printing process to illustrate how dreams are shaped by the subconscious and memory. <br><br> The narrative unfolds across four scenes—Awakening, Void Room, Confusion, and Reflection—each symbolizing a distinct stage in the evolution of awareness. `}
        // imagePaths={[
        //   "/img/projects/CG/i dream CG/dreamCG1.png",
        //   "/img/projects/CG/i dream CG/dreamCG3.png",
        //   "/img/projects/CG/i dream CG/videooout/mirror 4.mp4",
        //   "/img/projects/CG/i dream CG/videooout/eyeball 1.mp4",
        // ]}
        imagePaths={[
          {
            type: "image",
            src: "/img/projects/CG/i dream CG/dreamCG1.png",
            text: "Scene 1: Awakening The artificial brain begins to awaken as it is delicately formed from resin. Surrounded by an ocean-like expanse, the brain slowly gains consciousness. The fluidity of the water mirrors the formation of awareness, offering a serene and abstract vision of birth and emergence into reality.",
          },
          {
            type: "image",
            src: "/img/projects/CG/i dream CG/dreamCG3.png",
          },
          {
            type: "video",
            src: "/img/projects/CG/i dream CG/videooout/mirror 4.mp4",
          },
          {
            type: "video",
            src: "/img/projects/CG/i dream CG/videooout/eyeball 1.mp4",
          },
        ]}
        textAdditional={""}
        imageAdditional={[{ src: "/img/projects/CG/i dream CG/dreamCG4.png&quot;}]}
        creditsText={[
          "C R E D I T S",
          "YIFAN ZHUANG  <b>Concept & 3D ARTIST<b/>",
          "This is the CG created for interactive installation &#39;i dream, i dreamt&#39;.",
        ]}
        videoCreditsText={[]}
        specialThanksText={[]}
        additionalVideoSrc="https://player.vimeo.com/video/925292692?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479"
      />
    </div>
  );
};

export default About;

// export default function About() {
//   return (
//     <main>
//       <div
//         className="container"
//         style={{
//           width: "100vw",
//           height: "100vh",
//           position: "relative",
//           display: "flex",
//           margin: "0 auto",
//         }}
//       >
//         <iframe
//           src="https://player.vimeo.com/video/638304696?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479"
//           style={{
//             width: "100%",
//             height: "100%",
//             position: "absolute",
//             top: "0",
//             left: "0",
//           }}
//           allow="autoplay; fullscreen; picture-in-picture"
//           title="Vimeo video"
//         ></iframe>
//       </div>
//       <h2
//         style={{
//           marginTop: "80px",
//           fontSize: "50px",
//           textAlign: "center",
//           fontStyle: "italic",
//         }}
//       >
//         CG of &#39;i dream, i dreamt&#39;
//       </h2>
//       <p
//         style={{
//           margin: "20px",
//           textAlign: "justify",
//           marginLeft: "300px",
//           marginRight: "300px",
//           marginBottom: "100px",
//           marginTop: "80px",
//         }}
//       >
//         a dream generated by artificial brain &#39;no.01&#39;
//         <br />
//         <br />
//         <br />
//         In this immersive journey, we delve into the realm of &#39;Dreams of No.01,&#39;
//         where an artificial brain awakens to its own digital consciousness. The
//         video unfolds with the surreal scene of No.01&#39;s emergence into a
//         dreamlike state, guiding us through its memories. We witness its
//         inception, from the intricate process of being printed onto silicon
//         wafers to its assembly and eventual placement in the exhibit space.
//         Amidst this visual narrative, a distant voice accompanies us, murmuring
//         fragments of discourse as No.01 navigates its existential journey
//         <br />
//         <br />
//         <br />
//       </p>
//       <div
//         style={{
//           display: "flex",
//           justifyContent: "space-between",
//           flexWrap: "wrap",
//           objectFit: "cover",
//           padding: "20px",
//         }}
//       >
//         <img
//           src="/img/projects/CG/i dream CG/dreamCG1.png"
//           alt="Image 1"
//           style={{
//             width: "calc(50% - 100px)",
//             marginBottom: "10px",
//             marginLeft: "95px",
//           }}
//         />
//         <img
//           src="/img/projects/CG/i dream CG/dreamCG3.png"
//           alt="Image 2"
//           style={{
//             width: "calc(50% - 100px)",
//             marginBottom: "10px",
//             marginRight: "95px",
//           }}
//         />
//         <video
//           controls
//           autoPlay
//           style={{
//             width: "calc(50% - 100px)",
//             marginBottom: "20px",
//             marginLeft: "95px",
//           }}
//         >
//           <source
//             src="/img/projects/CG/i dream CG/videooout/mirror 4.mp4"
//             type="video/mp4"
//           />
//         </video>
//         <video
//           controls
//           autoPlay
//           style={{
//             width: "calc(50% - 100px)",
//             marginBottom: "20px",
//             marginRight: "95px",
//           }}
//         >
//           <source
//             src="/img/projects/CG/i dream CG/videooout/eyeball 1.mp4"
//             type="video/mp4"
//           />
//         </video>
//       </div>
//       <div style={{ marginTop: "100px", width: "100vw", height: "100vh&quot;}}>
//         <video
//           controls
//           autoPlay
//           style={{
//             width: "100vw",
//             marginBottom: "20px",
//           }}
//         >
//           <source
//             src="/img/projects/CG/i dream CG/videooout/mirror3.mp4"
//             type="video/mp4"
//           />
//         </video>
//       </div>
//       <div style={{ display: "flex", justifyContent: "space-between&quot;}}>
//         <div style={{ padding: "150px", marginLeft: "80px&quot;}}>
//           <p style={{ marginBottom: "15px&quot;}}>C R E D I T S</p>
//           <p style={{ marginBottom: "15px&quot;}}>
//             YIFAN ZHUANG <strong> Art Director & 3D ARTIST </strong>{&quot;"}
//           </p>
//           <p style={{ marginBottom: "15px&quot;}}>
//             This is the CG created for interactive installation &#39;i dream,
//             idreamt&#39;.{&quot;"}
//           </p>
//         </div>
//       </div>
//     </main>
//   );
// }
