import React from "react";
import PageInfo from "@/components/PageInfo";

const About = () => {
  return (
    <div>
      <PageInfo
        iframeSrc="https://player.vimeo.com/video/638304696?badge=0&autopause=0&player_id=0&app_id=58479"
        title="CG of 'i dream, i dreamt'"
        subtitle="a dream generated by artificial brain No.01"
        textContent={`In dreams of artificial brain <em>No.01</ em>, participants are taken on a journey exploring the emergence of an artificial brain developing digital consciousness. The installation combines CG visuals and footage of 3D printing process to illustrate how dreams are shaped by the subconscious and memory. <br /><br />The narrative unfolds across four scenes: Awakening, Void Room, Confusion, and Reflection, each symbolizing a distinct stage in the evolution of awareness.`}
        imagePaths={[
          { type: "image", src: "/img/projects/CG/i dream CG/dreamCG1.png" },
          {
            type: "video",
            src: "/img/projects/CG/i dream CG/videooout/eyeball 1.mp4",
          },
          { type: "image", src: "/img/projects/CG/i dream CG/dreamCG3.png" },
          {
            type: "video",
            src: "/img/projects/CG/i dream CG/videooout/mirror 4.mp4",
          },
        ]}
        textAdditional={""}
        imageAdditional={[{ src: "/img/projects/CG/i dream CG/dreamCG4.png" }]}
        creditsText={[
          "C R E D I T S",
          "YIFAN ZHUANG  <b>Concept & 3D ARTIST</b>",
          "This is the CG created for interactive installation 'i dream, i dreamt'.",
        ]}
        videoCreditsText={[]}
        specialThanksText={[]}
        additionalVideoSrc="https://player.vimeo.com/video/925292692?badge=0&autopause=0&player_id=0&app_id=58479"
      />
    </div>
  );
};

export default About;
