// export default function About() {
//   return (
//     <main>
//       <div
//         className="container"
//         style={{
//           width: "100vw",
//           height: "100vh",
//           position: "relative",
//           display: "flex",
//           margin: "0 auto",
//         }}
//       >
//         <iframe
//           src="https://player.vimeo.com/video/638304696?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479"
//           style={{
//             width: "100%",
//             height: "100%",
//             position: "absolute",
//             top: "0",
//             left: "0",
//           }}
//           allow="autoplay; fullscreen; picture-in-picture"
//           title="Vimeo video"
//         ></iframe>
//       </div>
//       <h2
//         style={{
//           marginTop: "80px",
//           fontSize: "50px",
//           textAlign: "center",
//           fontStyle: "italic",
//         }}
//       >
//         CG of 'i dream, i dreamt'
//       </h2>
//       <p
//         style={{
//           margin: "20px",
//           textAlign: "justify",
//           marginLeft: "300px",
//           marginRight: "300px",
//           marginBottom: "100px",
//           marginTop: "80px",
//         }}
//       >
//         a dream generated by artificial brain 'no.01'
//         <br />
//         <br />
//         <br />
//         In this immersive journey, we delve into the realm of 'Dreams of No.01,'
//         where an artificial brain awakens to its own digital consciousness. The
//         video unfolds with the surreal scene of No.01's emergence into a
//         dreamlike state, guiding us through its memories. We witness its
//         inception, from the intricate process of being printed onto silicon
//         wafers to its assembly and eventual placement in the exhibit space.
//         Amidst this visual narrative, a distant voice accompanies us, murmuring
//         fragments of discourse as No.01 navigates its existential journey
//         <br />
//         <br />
//         <br />
//       </p>
//       <div
//         style={{
//           display: "flex",
//           justifyContent: "space-between",
//           flexWrap: "wrap",
//           objectFit: "cover",
//           padding: "20px",
//         }}
//       >
//         <img
//           src="/img/projects/CG/i dream CG/dreamCG1.png"
//           alt="Image 1"
//           style={{
//             width: "calc(50% - 100px)",
//             marginBottom: "10px",
//             marginLeft: "95px",
//           }}
//         />
//         <img
//           src="/img/projects/CG/i dream CG/dreamCG3.png"
//           alt="Image 2"
//           style={{
//             width: "calc(50% - 100px)",
//             marginBottom: "10px",
//             marginRight: "95px",
//           }}
//         />
//         <video
//           controls
//           autoPlay
//           style={{
//             width: "calc(50% - 100px)",
//             marginBottom: "20px",
//             marginLeft: "95px",
//           }}
//         >
//           <source
//             src="/img/projects/CG/i dream CG/videooout/mirror 4.mp4"
//             type="video/mp4"
//           />
//         </video>
//         <video
//           controls
//           autoPlay
//           style={{
//             width: "calc(50% - 100px)",
//             marginBottom: "20px",
//             marginRight: "95px",
//           }}
//         >
//           <source
//             src="/img/projects/CG/i dream CG/videooout/eyeball 1.mp4"
//             type="video/mp4"
//           />
//         </video>
//       </div>
//       <div style={{ marginTop: "100px", width: "100vw", height: "100vh" }}>
//         <video
//           controls
//           autoPlay
//           style={{
//             width: "100vw",
//             marginBottom: "20px",
//           }}
//         >
//           <source
//             src="/img/projects/CG/i dream CG/videooout/mirror3.mp4"
//             type="video/mp4"
//           />
//         </video>
//       </div>
//       <div style={{ display: "flex", justifyContent: "space-between" }}>
//         <div style={{ padding: "150px", marginLeft: "80px" }}>
//           <p style={{ marginBottom: "15px" }}>C R E D I T S</p>
//           <p style={{ marginBottom: "15px" }}>
//             YIFAN ZHUANG <strong> Art Director & 3D ARTIST </strong>{" "}
//           </p>
//           <p style={{ marginBottom: "15px" }}>
//             This is the CG created for interactive installation 'i dream,
//             idreamt'.{" "}
//           </p>
//         </div>
//       </div>
//     </main>
//   );
// }

import React from "react";
import PageInfo from "@/components/PageInfo"; // Adjust the path as per your project structure

const Page = () => {
  return (
    <div>
      <PageInfo
        iframeSrc="https://player.vimeo.com/video/638304049?h=369837fcf8"
        title="i dream, i dreamt"
        subtitle='"All that we all see or seem
        <br />
        Is but a dream within a dream?"
        <br />
        -- <i>A Dream Within a Dream</i> Allan Kaprow'
        textContent={`"Dreamt, I Dream" unfolds as an immersive interactive
        artistic creation of mine, inviting you into the realm of dream
        generation through the artificial brain 'no.01'. By responding to
        stimuli from the external world initiated by participants, this
        installation unveils the subjective interplay of memory and brain
        activities. The surreal experience of transforming disconnected and
        incongruent signals into a visually cohesive narrative is rekindled.
        <br />
        <br />
        Various layers of animation and sound are activated through contact with
        3D-printed eye, nose, lip, ear, and hand replicas representing
        surrounding body organs. Equipped with cameras, electroacoustic
        transducers, and touch sensors, the installation processes live video
        and audience voices, fostering real-time interaction with participants.
        In this immersive journey, participants not only experience but also
        shape the dream generating process, blurring the lines between
        experiencer and creator.
        <br />
        <br />
        We exist as components within the dreams of others, just as we perceive
        others' existence as integral elements in our own dreams.`}
        imagePaths={[
          "/img/projects/interactive design/idream/idream1.jpg",
          "/img/projects/interactive design/idream/idream2.jpg",
          "/img/projects/interactive design/idream/idream3.jpg",
          "/img/projects/interactive design/idream/idream4.jpg",
        ]}
        creditsText={[
          "C R E D I T S",
          "YIFAN ZHUANG Creative Direction & Interaction Design & CG Animation",
          "HUA MA Technical Direction",
          "ZIYUE WANG Engineer",
          "SIYU MA Literature & Theory Advisor",
          "YINGTING HUANG Sound Design",
        ]}
        videoCreditsText={[
          "V I D E O   C R E D I T S",
          "YIFAN ZHUANG Direction & Shooting & Edit",
          "YINGTING HUANG Sound Design",
        ]}
        specialThanksText={[
          "S P E C I A L   T H A N K S",
          "KEITARO TSUCHIYA",
          "ETHAN SALLEY",
          "XIARU MENG",
          "YAN HE",
          "GEIST LAB",
          "GRADUATE SCHOOL OF KEIO MEDIA DESIGN",
        ]}
      />
    </div>
  );
};

export default Page;
